#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Builds the help pages served at http://<hostname>.local/help from the READMEs.

  README.zh-TW.md -> help/help-zh-TW.html
  README.md       -> help/help-en.html

Run it on your computer after editing a README and commit the output. The Pi
only serves these pre-built files, so it needs no Markdown library.

Usage: python3 build_help.py
Deps:  pip install markdown       (on the machine that builds, not the Pi)
"""

import os, re, sys, html
from string import Template

HERE = os.path.dirname(os.path.realpath(__file__))
OUT_DIR = os.path.join(HERE, "help")
PAGES = {   # lang -> (source, output, <html lang>, title, back link text)
    "zh-TW": ("README.zh-TW.md", "help-zh-TW.html", "zh-Hant", "使用說明", "返回設定"),
    "en":    ("README.md",       "help-en.html",    "en",      "Help",     "Back to settings"),
}

PAGE = Template("""<!doctype html>
<html lang="$html_lang">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$title · ePaper</title>
<!-- Generated by build_help.py from $source. Edit the README, not this file. -->
<style>
  :root {
    --bg: #f6f6f3; --card: #ffffff; --fg: #1d1d1b; --muted: #6b6b66;
    --line: #dcdcd6; --accent: #1f4fa3;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #161615; --card: #22221f; --fg: #ecece8; --muted: #a3a39c;
      --line: #3a3a36; --accent: #7fa7ee;
    }
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--fg);
         font: 16px/1.6 system-ui, -apple-system, "Noto Sans TC", sans-serif; }
  main { max-width: 920px; margin: 0 auto; padding: 0 16px 48px; }
  .bar { position: sticky; top: 0; z-index: 1; display: flex; justify-content: space-between;
         align-items: center; gap: 12px; padding: 10px 0; margin-bottom: 8px;
         background: var(--bg); border-bottom: 1px solid var(--line); }
  .bar a { color: var(--accent); text-decoration: none; }
  .langs a { padding: 4px 10px; border-radius: 6px; }
  .langs a.on { background: var(--accent); color: #fff; }
  .doc { overflow-wrap: anywhere; }
  .doc a { color: var(--accent); }
  .doc h1 { font-size: 1.5rem; margin-top: 2em; padding-bottom: .3em;
            border-bottom: 1px solid var(--line); }
  .doc h3 { font-size: 1.1rem; margin-top: 1.5em; }
  .doc img { max-width: 100%; height: auto; border-radius: 6px; }
  .doc blockquote { margin: 1em 0; padding: 4px 16px; border-left: 4px solid var(--line);
                    color: var(--muted); }
  /* wide tables scroll sideways instead of breaking words mid-way */
  .doc table { display: block; overflow-x: auto; border-collapse: collapse; margin: 1em 0;
               font-size: .9rem; overflow-wrap: normal; }
  .doc th, .doc td { border: 1px solid var(--line); padding: 6px 10px; text-align: left;
                     vertical-align: top; }
  .doc th { background: var(--card); }
  .doc code { font: .88em ui-monospace, SFMono-Regular, Menlo, monospace;
              background: var(--card); padding: 1px 4px; border-radius: 4px; }
  .doc pre { background: var(--card); border: 1px solid var(--line); border-radius: 8px;
             padding: 12px; overflow-x: auto; }
  .doc pre code { background: none; padding: 0; }
  .doc .mermaid { background: #fff; border-radius: 8px; padding: 12px; overflow-x: auto; }
</style>
</head>
<body>
<main>
<div class="bar">
  <a href="/">← $back</a>
  <span class="langs">
    <a href="help-zh-TW.html" class="$on_zh">中文</a>
    <a href="help-en.html" class="$on_en">English</a>
  </span>
</div>
<article class="doc">
$doc
</article>
</main>
<script src="https://cdn.jsdelivr.net/npm/mermaid@11.4.1/dist/mermaid.min.js"></script>
<script>
  // Flowcharts need the CDN; offline (e.g. in Wi-Fi setup mode) they stay as text.
  if (window.mermaid) {
    document.querySelectorAll("pre > code.language-mermaid").forEach(function (code) {
      var div = document.createElement("div");
      div.className = "mermaid";
      div.textContent = code.textContent;
      code.parentNode.replaceWith(div);
    });
    mermaid.initialize({ startOnLoad: false, theme: "default" });
    mermaid.run();
  }
</script>
</body>
</html>
""")


def github_slug(value, separator):
    """Heading ids the way GitHub makes them, so the READMEs' own TOC links
    (CJK headings included) work here too. Python-Markdown's default slugify
    drops every non-ASCII character."""
    v = re.sub(r"[^\w\- ]", "", value.strip().lower())
    return v.replace(" ", separator)


def gfm_tables(text):
    """GitHub lets a table start right under a paragraph line; Python-Markdown
    needs a blank line first. Code fences are left alone."""
    out, fenced, prev = [], False, ""
    for line in text.split("\n"):
        if line.lstrip().startswith("```"):
            fenced = not fenced
        elif not fenced and line.startswith("|") and prev.strip() and not prev.startswith("|"):
            out.append("")
        out.append(line)
        prev = line
    return "\n".join(out)


def build(lang):
    import markdown
    source, output, html_lang, title, back = PAGES[lang]
    with open(os.path.join(HERE, source), encoding="utf-8") as f:
        text = f.read()
    doc = markdown.markdown(
        gfm_tables(text), extensions=["tables", "fenced_code", "toc", "md_in_html"],
        extension_configs={"toc": {"slugify": github_slug}})
    # pages live in help/, images in img/: "../img/x" works from disk and,
    # served at /help-xx.html, resolves to /img/x
    doc = doc.replace('src="img/', 'src="../img/').replace('href="img/', 'href="../img/')
    page = PAGE.substitute(
        html_lang=html_lang, title=html.escape(title), source=source,
        back=html.escape(back), doc=doc,
        on_zh="on" if lang == "zh-TW" else "", on_en="on" if lang == "en" else "")
    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, output)
    with open(path, "w", encoding="utf-8") as f:
        f.write(page)
    return path


if __name__ == "__main__":
    try:
        import markdown  # noqa: F401
    except ImportError:
        sys.exit("needs the Markdown library: pip install markdown")
    for lang in PAGES:
        print("wrote", os.path.relpath(build(lang), HERE))
